### ISSUE TITLE
Severe Issue on Edge and Firefox when selecting the Marker

### ISSUE THREAD

**Issue by dleger** [iatkin/leaflet-svgicon#8] opened 2018-03-16 08:44 UTC
Hi,

There is a severe bug when selecting the marker on the map with Edge or Firefox.

http://iatkin.github.io/leaflet-svgicon/

If you put the mouse on the RIGHT of the icon, you clearly see that the "select hand" is triggered instead of the flat hand. So, being on the right of the icon is like to be ON the icon. The issue is not here with Chrome of Opera.

Thanks

**Comment by iatkin** [comment] 2018-06-08 19:25
That should be fixed now. I wouldn't describe it as a severe issue though since it was strictly visual and caused by a small error in Firefox's and Edge's SVG support.

**Closed as completed by iatkin** 2018-06-08 19:25 UTC

**Comment by dleger** [comment] 2018-06-08 19:27
It was not strictly visual. When editing a POI in my App, it was not possible to correctly select the POIs because of this. But many thanks for fixing the bug ;) In the meantime, I've used PNGs instead.
