### ISSUE TITLE
circle not anchored correctly with  custom iconSize

### ISSUE THREAD

**Issue by simon1tan** [iatkin/leaflet-svgicon#15] opened 2018-12-29 19:24 UTC
Changed iconSize to [48,48] and creates a marker where the circle is offset to the left. Circle should stay centered. When I manually set the circleAnchor to [24,24], the circle is centered correctly.

**Comment by iatkin** [comment] 2019-01-11 15:43
What version of Leaflet are you using and what browser? The code sets the circleAnchor to iconSize/2 if one is not provided.

**Comment by iatkin** [comment] 2019-02-06 13:15
Hi. I'm closing this issue because I've been unable to reproduce it with any size icon.

**Closed as completed by iatkin** 2019-02-06 13:15 UTC
